name: "Publish to PyPI"
description: "Publishes the package to PyPI"

inputs:
  pypi-token:
    description: "PyPI API token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ inputs.pypi-token }}