name: Build

on:
  workflow_call:

jobs:
  use-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python & Dependencies
        uses: ./.github/actions/use-python.yml

      - name: Install pypa/build
        run: python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/