name: "Notify"
description: "Sends a notification"

inputs:
  api-key:
    description: "API key for alerts"
    required: true
  alert-type:
    description: "Either build|release|publish"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Build Alert
      working-directory: ./sample
      run: |
          export PYTHONPATH=../src
          python github_alert.py --${{ inputs.alert_type }}
      env:
        APIALERTS_API_KEY: ${{ inputs.api-key }}
      shell: bash
