name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests

      - name: Install pypa/build
        run: python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Send Build Alert
        working-directory: ./sample
        run: python sample/github_alert.py --release
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Send Build Alert
        working-directory: ./sample
        run: python sample/github_alert.py --publish
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}