name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/apialerts
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup
        with:
          python-version: 3.13

      - name: Test
        uses: ./.github/actions/test

      - name: Build
        uses: ./.github/actions/build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Notify
        uses: ./.github/actions/notify
        with:
          api-key: ${{ secrets.APIALERTS_API_KEY }}
          alert-type: 'publish'