name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/use-build.yml

  test:
    needs: build
    uses: ./.github/workflows/use-test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Send Publish Alert
        uses: ./.github/workflows/use-notify.yml
        with:
          alert_type: '--publish'