name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/actions/use-build.yml

  test:
    needs: build
    uses: ./.github/actions/use-test.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Publish Alert
        uses: ./.github/actions/use-notify.yml
        with:
          alert_type: '--release'

      - name: Publish to PyPi
        uses: ./.github/actions/use-publish.yml

      - name: Send Publish Alert
        uses: ./.github/actions/use-notify.yml
        with:
          alert_type: '--publish'