name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/use-build.yml

  test:
    needs: build
    uses: ./.github/workflows/use-test.yml

  publish:
    needs: test
    uses: ./.github/workflows/use-publish.yml

  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Send Publish Alert
        uses: ./.github/workflows/use-notify.yml
        with:
          alert_type: '--publish'