name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup
        with:
          python-version: 3.13

      - name: Test
        uses: ./.github/actions/test

      - name: Build
        uses: ./.github/actions/build

#      - name: Notify
#        uses: ./.github/actions/notify
#        with:
#          api-key: ${{ secrets.APIALERTS_API_KEY }}
#          alert-type: 'build'
