name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/actions/use-build.yml

  test:
    needs: build
    uses: ./.github/actions/use-test.yml

  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Build Alert
        uses: ./.github/actions/use-notify.yml
        with:
          alert_type: '--build'